### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by absdnd** [ThibaultGROUEIX/3D-CODED#29]
Hi, 

Thank you for the publishing your code with extensive documentation. 

I have a small query,  when I run `./data/download_dataset.sh`,  `datas_surreal_test.pth` and `data_surreal_train.pth` are downloaded. However, the download is incomplete which leads to the following unpickling error. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vision/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/home/vision/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

I would be grateful if you could provide some guidance on how to resolve the same.

**Comment by ThibaultGROUEIX** [comment]
Hi @absdnd 
Sorry I missed this. This is not good ! I hope it is a download issue,
Were you able to fix it?
Best regards,
Thibault
