### ISSUE TITLE
Problem executing the demo - `GLIBCXX_3.4.29' not found 

### ISSUE THREAD

**Issue by chibi03** [ThibaultGROUEIX/3D-CODED#51]
Hello!
I've been trying to setup the repository but keep failing in getting the chamfer_distance to work. I set up an anaconda environment as instructed and my system CUDA has version 10.1 and GCC 9.3.0. 
Some more of my system specs:
- Manjaro Linux w/ Kernel 5.10.151
- System python 3.10

When loading the chamfer_distance cpp_extension the following error occurs:
```
Traceback (most recent call last):
  File "inference/correspondences.py", line 18, in <module>
    import dist_chamfer as ext
  File "./extension/dist_chamfer.py", line 11, in <module>
    "/<path>/3D-CODED/extension/chamfer.cu"])
  File "/<path>/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "<path>/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/<path>/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 968, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/<path>/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/<path>/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /<path>/anaconda3/envs/pytorch-3D-CODED/lib/python3.7/site-packages/torch/../../../libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/torch_extensions/chamfer/chamfer.so)
(pytorch-3D-CODED) 

```
Could you please advise me on how I could solve this?

**Comment by chibi03** [comment]
I was able to fix the issue. It only occurred if I don't install chamfer_distance with setup.py and if I did install it I got the error `undefined symbol: _ZNSt19basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev` . 
I was able to fix the undefined Symbol error using CUDA 10.0. In case somebody else has this issue I was not able to get it to work with CUDA 10.1, maybe installing 10.0 will solve the issue for others as well.
